In [1]:
#as we have lot of methods to train our data like randomForestClassifier , logistic regression, linear regression,tree classifier, svm etc hence in order to know the best best method to train our data is tusing cross validation
#new technique to train our model apart from train test split is KFold cross validation 
# in this we divide our sample into folds like if we have 100 samples then let one fold have 20 samples => 5 folds we will have
# now we will train our model iterations wise like in first we use fold one for testing and remaining for training similarly in second 2nd for testing and remaining for training nd repeat this process
# and finally we will take the average of all the accuracies we got in each iteration
# this is a very good technique to train our model as it gives us the best accuracy and also helps us to avoid overfitting
# we will use KFold cross validation to train our

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
digits=load_digits()
import warnings
warnings.filterwarnings("ignore")



In [2]:
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)

In [3]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9638888888888889

In [4]:
svm=SVC(kernel='linear')  # You can also try 'rbf', 'poly', etc.
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9722222222222222

In [5]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)
#problem with these methods is that every time when we run the split the different data will be available for training and testing which changes the score of the model every time whenever we run the model


0.9666666666666667

In [6]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3) # n_splits is the number of folds you want to create
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
#defining the generic function to calculate the score as per the method supplied
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [9]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

0.9638888888888889

In [10]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9888888888888889

In [11]:
from sklearn.model_selection import StratifiedKFold
#it is better than kFold b/c when we divide our folds it will divide it in a uniform way with proper classification category
folds = StratifiedKFold(n_splits=3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
scores_1=[]
scores_svm=[]
scores_rf=[]

for train_index, test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_1.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))


In [13]:
scores_1

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [14]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [15]:
scores_rf

[0.9315525876460768, 0.9348914858096828, 0.9198664440734557]

In [16]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [17]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])