In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import warnings
warnings.filterwarnings('ignore')

df=pd.DataFrame({
    'area':[2600,3000,3200,3600,4000],
    'price':[550000,565000,610000,680000,725000]
})
reg=linear_model.LinearRegression()
reg.fit(df[['area']],df.price)
reg.predict([[5000]])

array([859554.79452055])

In [2]:
import pickle
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [3]:
with open('model_pickle','rb') as f:
    mp=pickle.load(f)


In [4]:
mp.predict([[5000]])

array([859554.79452055])

In [5]:
# using joblib method when you have more numpy arrays this method is more efficient then pickle but both gives same functionality

import joblib 
joblib.dump(reg,'model_joblib')


['model_joblib']

In [6]:
mj=joblib.load('model_joblib')
mj.predict([[5000]])

array([859554.79452055])